# Generated by Django 5.2 on 2025-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_by_telegram_user_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_by_telegram',
            field=models.BooleanField(default=True),
        ),
    ]
