# Generated by Django 5.2 on 2025-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_verified_by_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_by',
            field=models.BooleanField(default=False),
        ),
    ]
