# Generated by Django 5.2 on 2025-05-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified_by',
            new_name='is_verified',
        ),
    ]
