# Generated by Django 5.2 on 2025-07-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified_by_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
