# Generated by Django 5.2 on 2025-06-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.tourcategory'),
            preserve_default=False,
        ),
    ]
